name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn -B package -DskipTests

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: sitavares/back-end-tophair:latest

  deploy:
    runs-on: self-hosted
    needs: docker
    steps:
      - name: Pull Docker image
        run: sudo docker pull sitavares/back-end-tophair:latest

      - name: Stop Docker container
        run: sudo docker stop ci-example || true

      - name: Remove Docker container
        run: sudo docker rm ci-example || true

      - name: Run Docker container
        run: sudo docker run --name ci-example -d -p 8080:8080 sitavares/back-end-tophair:latest